import { PrimeReactProviders } from "@/app/providers";
import Layout from "@/layout/layout";
import "@/styles/globals.scss";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "primereact/resources/primereact.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link id="theme-css" href={`/themes/lara-dark-teal/theme.css`} rel="stylesheet"></link>
      </head>
      <body className={poppins.className}>
        <PrimeReactProviders>
          <Layout>{children}</Layout>
        </PrimeReactProviders>
      </body>
    </html>
  );
}
